import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { MarkdownContent } from "@/components/MarkdownContent";
import { ShareMenu } from "@/components/ShareMenu";
import { SiteLikeButton } from "@/components/SiteLikeButton";
import { getPollAnalysisBySlug } from "@/lib/public-participation/analysis";
import styles from "../../page.module.css";

type PageProps = {
  params: Promise<{
    slug: string;
  }>;
};

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const { analysis } = await getPollAnalysisBySlug(slug);

  return {
    title: analysis ? `${analysis.title} - Kenyan Bill` : "Analysis Report",
    description: analysis?.summary || "Public sentiment report on the Finance Bill 2026.",
  };
}

export default async function AnalysisDetailPage({ params }: PageProps) {
  const { slug } = await params;
  const { analysis, error } = await getPollAnalysisBySlug(slug);

  if (!analysis || error) {
    notFound();
  }

  return (
    <div className={styles.page}>
      <header className={styles.hero}>
        <p className={styles.kicker}>Sentiment Analysis • {new Date(analysis.analyzed_at).toLocaleDateString('en-KE', { dateStyle: 'long' })}</p>
        <h1>{analysis.title}</h1>
        <div className={styles.analysisMetaInline}>
          <strong>{analysis.poll_count} Polls</strong>
          <strong>{analysis.vote_count.toLocaleString()} Total Votes</strong>
        </div>
        <p className={styles.lead}>{analysis.summary}</p>
        <div className={styles.actions}>
          <Link href="/public-participation/analysis">← Back to all reports</Link>
          <div style={{ display: 'flex', gap: '16px', alignItems: 'center' }}>
            <SiteLikeButton targetType="analysis" targetId={analysis.id} initialLikeCount={analysis.like_count} />
            <ShareMenu 
              title={analysis.title} 
              text={analysis.summary} 
              urlPath={`/public-participation/analysis/${slug}`} 
            />
          </div>
        </div>
      </header>

      <section className={styles.reportContent}>
        <MarkdownContent content={analysis.content} />
      </section>

      <footer className={styles.reportFooter}>
        <div className={styles.footerNote}>
          <h3>About this analysis</h3>
          <p>
            This report was automatically generated by this platform based on live poll data submitted by Kenyan citizens. 
            The analysis provides a snapshot of the national mood to encourage deeper civic engagement and understanding.
          </p>
        </div>
        <div className={styles.actions}>
          <Link href="/public-participation">Ready to vote? View active polls</Link>
        </div>
      </footer>
    </div>
  );
}
